pipeline:
  -
    - v4l2src device=/dev/video0
    - video/x-raw,format=RGB,width=640,height=480,framerate=30/1
    - tee name=t
    - videoconvert
    - timeoverlay
    - omxh264enc target-bitrate=2000000 control-rate=variable
    - rtph264pay config-interval=1 pt=96
    - udpsink host=10.49.52.168 port=5004
  -
    - t.
    - appsink max-buffers=1 name=sink
width: 640
height: 480
port: 7000
