pipeline-for-appsrc: # name of the appsrc MUST be 'sink'
  -
    - udpsrc address=224.1.1.1 port=25004 caps="application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264"
    - rtph264depay
    - avdec_h264
    - videoconvert
    - jpegenc
    - appsink max-buffers=1 name=sink
pipeline-for-execute:
  - "udpsrc port=15004 ! udpsink host=224.1.1.1 port=25004 ttl-mc=0 loop=true" # split by ip multicast
  - "udpsrc address=224.1.1.1 port=25004 ! udpsink host=localhost port=5004" # relay to janus
port: 7000
