pipeline:
  -
    - udpsrc port=15004 caps="application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264"
    - rtph264pay
    - avdec_h264
    - videoconvert
    - jpegenc
    - appsink max-buffers=1 name=sink
width: 640
height: 480
port: 7000
